let config = {
  // 部分ins用户设置需关注后才可获取, 可配置用户cookie 键为"sessionid"
  sessionCookie: '',

  // 抓取用户列表
  userFollow: '',
  tagList: ['color'],
  // 关键词内容抓取
  tagUsers: ['私房'],
  // isTag: true,
  isTag: false,

  // 本地地址
  savePath: './Media/',

  maxMediaOccurs: 18,
  // 时间间隔
  timeout: 30000,
  // 本地代理
  proxy: 'http://127.0.0.1:1087',

  igrCAErr: false,
  // 用户名
  downUsers: [
    'mykhailo_rychkov',
    'watercolor.zone',
    'discoverglobe',
    'katya_mihailina_07',
    'bro_ka_li',
    'juliabarminova',
    'nadja.leutloff',
    'schmoedraws',
    'iraville',
    'illustration_best',
    'misselvani',
    'aquarryl',
    'urbankate_in_ca',
    'watercolor_guide',
    'heikala',
    'summersunhomeart',
    'water.lesson',
    'katyastrog',
    'floralarthub',
    'noellecurtis.art',
    'daniellelanslots_art',
    'nanraefineart',
    'beckystarsmore',
    'youdesignme.de',
    'dearannart',
    'rosies.sketchbook',
    'urbankate_in_ca',
    'greemorning',
    'beckystarsmore',
    'vianka_guinaz',
    '2018.wc.japan',
    'mylenemolo',
    'watercolor_daily',
    'art.istic.tips',
    'eat_it__paint_it',
    'dang_go',
    'watercolor_guide',
    'ninathidalgo',
    'thiswritingdesk',
    'watercolor_libran',
    'carlacochua',
    'artbybianca',
    'philkim.dh',
    'lettersoflovebyjo',
    'lichingheng',
    'veryhyun7',
    'philkim.dh',
    'somi.still',
    'misselvani',
    'virtuosouniverse',
    's__z_n',
    'artbybroling',
    '@marias_mix',
    'artbybroling',
    '@jameygoodmanart',
    'watercolourweekly',
    'bordergrime',
    'claudiaradvanyi',
    'artwork_life24h',
    'itz_vys____z',
    'vish.bhamee',
    'thiswritingdesk',
    'lexicon.studio',
    'letter_zen',
    'xtina_gavrilova_art',
    'lillys_studio',
    'hans.susantio',
    'art.discover',
    'neguin38_don',
    'xiinshine',
    'anna_n_watercolors',
    'laviniartttstudio',
    'anna_n_watercolors',
    '@laviniartttstudio',
  ],
};

module.exports = config;
